// GET
export const GET_ERROR = 'GET_ERROR'
export const GET_ALL_PRODUCT_DIVISION = 'GET_ALL_PRODUCT_DIVISION'
export const GET_BRAND_LIST = 'GET_BRAND_LIST'
export const GET_ALL_CARD = 'GET_ALL_CARD'
export const GET_SINGLE_CARD = 'GET_SINGLE_CARD'
export const GET_ALL_BRAND = 'GET_ALL_BRAND'
export const GET_ALL_STATUS = 'GET_ALL_STATUS'
export const GET_ALL_AUTHORITY = 'GET_ALL_AUTHORITY'
export const GET_SINGLE_AUTHORITY = 'GET_SINGLE_AUTHORITY'
export const GET_ALL_AUTHORITY_ROLE = 'GET_ALL_AUTHORITY_ROLE'
export const GET_ALL_LOCATION = 'GET_ALL_LOCATION'
export const GET_ALL_USER_NOTIFICATION = 'GET_ALL_USER_NOTIFICATION'
export const GET_ALL_AUTHORITY_BY_ROLE_ID = 'GET_ALL_AUTHORITY_BY_ROLE_ID'

// POST
export const CREATE_CARD = 'CREATE_CARD'
export const CREATE_AUTHORITY = 'CREATE_AUTHORITY'
export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION'

// UPDATE
export const UPDATE_CARD = 'UPDATE_CARD'
export const UPDATE_CARD_MESSAGE = 'UPDATE_CARD_MESSAGE'
export const UPDATE_CARD_STATUS = 'UPDATE_CARD_STATUS'
export const UPDATE_AUTHORITY = 'UPDATE_AUTHORITY'
export const UPDATE_AUTHORITY_MESSAGE = 'UPDATE_AUTHORITY_MESSAGE'
export const UPDATE_NOTIFICATION_IS_READ = 'UPDATE_NOTIFICATION_IS_READ'

// DELETE
export const DELETE_CARD = 'DELETE_CARD'
export const DELETE_AUTHORITY = 'DELETE_AUTHORITY'

// CARD Methods
export const REQUEST_APPROVAL = 'REQUEST_APPROVAL'
